### ISSUE TITLE
Remove supervisord

### ISSUE THREAD

**Issue by wernight** [timhaak/docker-plex#13]
supervisord doesn't handle PID1 zombie collection. It's also not needed here. Could directly start plex and flag `restart: always` if one wishes to.

**Comment by timhaak** [comment]
I'm aware of this. 

I was directly starting it. Then had some people have a problems with that. (Assume they are using the built in update feature. Which would break with out this.)

Is this currently causing a problem for you?

If so how? 

Having it in is not best practice but don't have the time right now to work out how to put a correct init system in.

If your keen I'm happy accept a pull request :) or you'll have to wait till have I have enough free time :) (Going to be a while)

So back to the question what is it breaking for you? If its something critical I'll see if I can find some time and get a proper init system. (Was looking at s6).

**Comment by wernight** [comment]
I would avoid having a proper init system. I know it's possible but usually I found you can just directly call the daemon you need to run.

I wonder how it's breaking the upgrade system if you launch with `--restart=always`. Would you remember what breaks?

**Comment by timhaak** [comment]
Ok so your answer is basically. I would like this to work like this for me.

I can't see why this would break for anyone else.

So as I have had people have problems with out the supervisor I will not be changing it to meet your requirement as you did not give me an example of how this is actually causing a problem for you.

So I'm going to close this. At some point I'll add an init system if I have time. Right now it should actually work.

Unless you can actually give me a problem that this is causing you? Since you haven't I'm assuming you've just been reading on line and are quoting something you've read back.

Please feel free to fork the project and alter as you see fit and then do your own build? It isn't hard.

That way your changes worn't affect other people which you don't seem to care about over your own.
