### ISSUE TITLE
Should not run as root

### ISSUE THREAD

**Issue by wernight** [timhaak/docker-plex#14]
[Docker container don't contain](https://opensource.com/business/14/7/docker-security-selinux)

**Comment by timhaak** [comment]
You obviously didn't read the whole article.

**If you are not running Docker on a multi-tenant system, and you are using good security practices for the services running within a container, you probably do not need to worry.**

Unless you are running this in a multi-tenant environment? 

If you are you should be building your own images. Or if you would like to use these then helping improve with a pull request.

So going forward if you want to log an issue. I would like you to specify what exactly the problem is that you are experiencing?

**Comment by timhaak** [comment]
I've altered it that plex is no run as the plex user.

If you would like further changes you will have to send a pull request with the changes.

If your changes don't include some kind of init system I'll reject them.

**Comment by wernight** [comment]
There are other issues like access to kernel, and just in general. Also he said just below "Just assume that privileged processes running within the container are the same as privileged processes running outside of the container." So if there is a nginx/php/... running as www-data I would find it fine, but I would not run them as root. Same for plex. Why make it run as root anyway when one gain a lot more safety by just making it run as another user.

Anyway since you don't care, I won't even bother.

**Comment by timhaak** [comment]
Well If you had looked you would see that I had changed plex running as root.

Though the bash still is as it needs rights to ensure that the files have the correct ownership.

What irritates me is that you spout off on all the things I should change and work on but contribute nothing.

If you cared like you say you did you would provide a pull request or put effort in fix. Instead you complain and then effectively expect me to put effort in to fix.

I put this together to as I needed it and thought it would be good to share in case someone else wanted something to work from. I gain nothing from it besides the personal use of Plex.

Though I still put in effort when people mention something that is breaking for them. Why because its nice to help but not because I have to.

From both your tickets I gather you want this to work for a specific pattern you have. You actually don't seem to care that some of the decisions on how this works was done to make it work for the general case and not your specific case. 

No I am not going to make changes that I think may break it for some other people just so you can get what you seem to be expecting. It may not but there is a good chance it will. If it does you will not be the person who then will look at it and try and fix it for the others.

You whole attitude seem to be centred on what you want and how I must fix things to make your happy and this is what is irritating me about you.

Is this repo perfect. Hell no. Why because I threw it together initially to get it to work for me. I've then added fixes as people have brought things out. I accepted pull requests when I think it will improve the system. I don't get paid for it. I gain nothing out of it but extra work in helping others.

If your really unhappy with this then go and do a better one. Send me the link create a build on the index.

If I think its better I'll happily point people at it as a better alternative.

**Comment by wernight** [comment]
@timhaak Sorry I missed your change (it wasn't clear from your reply nor was it linked to this ticket). I didn't send a PR and usually don't until at least one of the owner agrees on the issue and possible solution (you can see from my history that I contribute quite a lot). Also I don't have a specific case for it to work, just care to make it work safely for everyone and improve what seems the current main Docker image for plex. Both tickets are not to fit my custom needs but to make things works well in general for everyone. In the end I made my own, which is currently not promoted. If you'd like to take a look it's at: https://registry.hub.docker.com/u/wernight/plex-media-server/ of course it's not as mature as yours so people may still have a few bumps.

**Comment by timhaak** [comment]
Hi

I've added a link. 

Two things. 

1. As your worried about security you should be doing a dist-upgrade to ensure the base system is fully up to date. Though plex should be standalone it may call something else. Ie the problems when bash had its vulnerabilities.

2. You may want to move to debian wheezy as the base as it will mean far smaller images for people to pull down.

**Comment by wernight** [comment]
Thanks for the suggestions. I see Debian is about half size which is good. [`dist-upgrade` isn't recommended](https://docs.docker.com/articles/dockerfile_best-practices/) and usually those should come from the image directly. In any case the exposed surface is mostly plex, so the risk is mostly that plex gets compromized.

As far as I know, the user ID within the container is different from the one outside, so I find it very strange that actually there isn't a kind of helper to have a user ID existing only in the container and have no right outside it. Anyway it's outside scope for now.

**Comment by timhaak** [comment]
Only as it may break your build, but since you said you were worried about security then its one of the things you should do :). 

Either you care about security or you don't. Which is it?

**Comment by wernight** [comment]
I care about it enough to remove what is risky for the entire system. If containers could really contain that'd be awesome! I know it's always getting closer.

That said even though `dist-upgrade` is good practice outside containers, inside it a whole other story. Caching makes that this command has no effect especially on automated builds (unless I put something to break cache which sounds actually really bad).

The better practice would be for someone to use that image and run `dist-upgrade` periodically on it. I assume, but didn't verify, that the base image also gets security fixes periodically (which comes from http://crosbymichael.com/dockerfile-best-practices-take-2.html practice and I see frequent updates to Debian base image).

More worrying if you're looking at Docker security, is that user `plex` is running outside the container as a complete different user, and that seems bad to me.

**Comment by timhaak** [comment]
Will do
