### ISSUE TITLE
Auto Upgrade

### ISSUE THREAD

**Issue by stokkie90** [timhaak/docker-plex#21]
Can you make it possible to auto update the plexmedia package afeter a restart of the container for example.

maybe put it in the start.sh script. (apt-get update apt-get upgrade)

**Comment by chuckleb** [comment]
That's not really easy to do since the containers are baked with whatever is current at the build. Restarting and having it update would be possible if you put in the init scripts for it to update the image, but you run the risk of breaking the build. The start.sh is executed once during the build.

One of the benefits of the container is that they are tested and versioned, allowing you to step back to a known working point. The stability is great for many services. If you are looking for a more quickly updated plex, you could either install it from a package or pull the git source and build it yourself, it's very easy to do. I think Tim posted that the image is rebuilt nightly as is.

**Comment by timhaak** [comment]
Yes not really the correct way to use docker. Everything should be self contained and only settings should run on start. 

I have a cron the at 3am runs a script that does a docker pull, then docker stop then docker rm, then docker start.

Actually the only reason that I do the pull nightly my side is so that I'll see if something breaks.

Though actually been surprisingly stable. 

Yup image is rebuilt nightly.
