### ISSUE TITLE
--net="host" doesn't seem to work on Docker 1.9.1

### ISSUE THREAD

**Issue by inhumantsar** [timhaak/docker-plex#43]
I've been running this image on FC22 (and Debian 7 previously) without issue. Updated to 1.8.2 last year, no problems. Updated to 1.9.1 today and had to remove --net="host" to get the ports to map. This might be a Docker issue in general, but thought y'all should know in case the docs need updating now.

**Comment by flungo** [comment]
Docker has made some updates in the way that networking works however, using `--net=host` should still work. With regards to when you say "to get the ports to map", when using `--net=host` the `-p` flags should be ignored (this may be what has changed) because when using `--net=host` no port forwarding is needed.

The documentation does need to be updated to not include the redundant `-p 32400:32400` on the example using `--net=host`. I will test later to see if Docker now throws an error when trying to use the two together, but if you need the `--net=host` functionality, try removing the `-p 32400:32400` instead.

**Comment by inhumantsar** [comment]
Ok fair enough, that makes some sense. The problem I was having was that with --net=host, the running container was inaccessible on <Host_IPs>:32400. When I noticed that the ports weren't being mapped, I figured that was why. I'll try it again with --net=host and no -p.

**Comment by inhumantsar** [comment]
Just reporting back, `--net=host` without `-p` definitely works. As does `-p` without `--net=host`. Specifying both resulted in the container being inaccessible on 32400.
