### ISSUE TITLE
Allowed networks set to wrong IP range by default

### ISSUE THREAD

**Issue by adampolar** [timhaak/docker-plex#54]
Hi,

I've used this dockerfile for a while but recently I had to rebuild it. I also did not have any config prepared. The default config (in `Preferences.xml`) was set to `allowednetworks="172.17.0.0/16"` which was the ip of the `docker0` interface but meant that I couldn't configure the server from the web interface and the  container was running on the headless server. I then configured `Preferences.xml` so that `allowednetworks="192.168.0.0/16"` (I also changed `PublishServerOnPlexOnlineLineKey="0"`) and it worked fine. Should the default configuration be this or should some instructions be provided so that people don't have to figure this out? (Or have I made an error following the instructions?)

**Comment by vvhof** [comment]
Hello adampolar,

does this happen with the most recent version?

#45 
bb1390dcc8f23d7169e5bad71bae2390e16ecf33

**Comment by adampolar** [comment]
Hi vvhof,

I just pulled the latest from the master branch, [f5421](https://github.com/timhaak/docker-plex/commit/f5421b1dd2fcfa1a1edac57b157a282c558ece5c) is what I built from. I did not supply the `PLEX_ALLOWED_NETWORKS` environment variable. Is this now mandatory?

**Comment by flungo** [comment]
It shouldn't be mandatory under most scenarios:
- If you are accessing the container IP from the host, then you should be communicating with it using the bridge interface on the host to communicate with the container which is inside of the default value for `allowedNetworks`
- If you use port forwarding then by default, your source IP is masqueraded to the host machine's IP within the docker bridge which will be accepted by the container's default value for `allowedNetworks` - same as above
- If you are using `--net=host` it will add all non-default routes (and hence all local subnets) to the `allowedNetworks` attribute.

How are you trying to access the container? Do you have `ip_masq=false` or `iptables=false` set on your docker daemon?

Unless there is an unforeseen issue in one of the cases above it should be working.

**Comment by adampolar** [comment]
Hi flungo,

I'm accessing the container from a remote machine, as it's a headless server. I am using the '-p' port forwarding switch in the run command. I haven't set those flags. My relevant iptables output is as follows;
In my postrouting chain 
`MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0`           
`MASQUERADE  tcp  --  172.17.0.1           172.17.0.1           tcp dpt:32400`
And in my docker chain 
`DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:32400 to:172.17.0.1:32400`

I haven't really got any special configuration on the box this is on, be it iptables (to be honest I don't know iptables very well at all, I usually use ufw for configuring my firewall rules) or the docker daemon.

**Comment by flungo** [comment]
Okay, so that does make sense and is correct. DSTNAT won't change the source so from an external PC the default won't allow access (except where using `--net=host`). In the case of using port forwarding, this matches the default plex configuration (which is localhost only) - but this does bring up two other points for consideration:
- A `SKIP_PREFERENCES_CONFIG` which will allow people to stop any changes being made to `Preferences.xml` if they wish to manually configure and not have anything overridden automatically at startup. Possibly even a `SKIP_X` for each individual preference that would otherwise automatically be detected.
- Should we match the default configuration exactly such that if `--net=host` is used, it locks back down to `127.0.0.0/8` so that it is not exposed to the rest of the network unless requested. If so, how do you detect `--net=host`: initial thought is to use `ethtool` to detect if there is `peer_ifindex` on any interface.

In response to the issue here, I would say that in this scenario you will need to set `PLEX_ALLOWED_NETWORKS` and that this is in-line with the default configuration with Plex running in a normal environment.

**Comment by flungo** [comment]
@adampolar Are you happy with this behavior and that it actually matches the behavior of the plex distribution?

If so I will look into implementing the two other suggestions I made and see what the other developers think as well as checking that the documentation matches this behaviour.

**Comment by adampolar** [comment]
Hi flungo, sorry for not replying. I've never used Plex outside of this docker container so I didn't realise that this is the usual behaviour of Plex, my personal feeling is that could be useful in the "instructions to run" section, but that's just my opinion and if the typical user already knows Plex behaves like this it may be obvious to them. Happy to close if you are.

**Comment by flungo** [comment]
@adampolar No worries. I will check the documentation when I get a chance, and see if it can be made any clearer and close this issue with any changes made there. Thanks for the feedback.
