### ISSUE TITLE
can't linkthis thing to my account

### ISSUE THREAD

**Issue by boistordu** [timhaak/docker-plex#59]
can't link like your version plexpass.

**Comment by boistordu** [comment]
I did find your problem. I don't know for how long you  you didn't update your docker but the preferences.xml which is created, doesn't work because of the authorized networks I think. 
your preferences.xml did create this allowedNetworks="172.17.0.0/16"
which of course not good since the host is on a different NAT network and anyway you point to the internal network of the host of docker so even if the packet goes from a nat up and goes through the host, the packet never reach his destination because the plex won't authorize the origin of the packet. 
in the linuxserver docker this line is not created at all so it works better.

**Comment by timhaak** [comment]
Hi

Have you tried either of the variables bellow?

PLEX_DISABLE_SECURITY

PLEX_ALLOWED_NETWORKS

Should solve this for you I think?

**Comment by boistordu** [comment]
but you didn't explain in your  readme how to put theses variables... if it was in the preferences.xml of plex itself or if it was in something else like a docker config file. 
+ I think you should remove the allowed networks option since as I explained earlier, the plex won't never recognized the real nat network that we are using ... So it's a waste of time to have to change the option at start. It's a misconception of yours, I do'nt see why the allowed networks would be the internel network of the host where docker is installed... I don't see nor the point nor the logic behind it.

**Comment by boistordu** [comment]
So I think you should really change it at start and not act as it is not a problem. Or at least add a line in your readme

**Comment by timhaak** [comment]
Unfortunately as mentioned to you in your other issue this is all done purely on a volunteer basis. 

So out time is limited and there is only so much we can do.

The basic's are generally designed to work for the standard install.

As you are using it for multiple plex's I'm assuming that's not the case on your side.

If you would like to help improve please do.

**Comment by boistordu** [comment]
I can totally understand of volunteer basis. And I could totally understand this thing if it was a complicated matter. But again on any installation I can't see that work. 
Standard utilisation require a personal nat, since you won't pay a provider pro server on ovh or digital ocean server because you wan't to be able to hosting all your tv shows, movies (illegally obtained) or personal movies or even those which you have copy from your personal bluray or dvd. So of course the host of my docker is on a personal NAT, but that's not pretty special as configuration, that seems even logic. 
By default, your configuration suggest that only packets can come from 172.17.0.0 which is the internal NAT of the host of docker. And THAT's the case on EVERY single one installation in the world of docker. Because docker needs to put in place a personal nat to separate the dockers from the actual network which is internet or a personal NAT. So if you can't allow only this network by default, how will you reach the plex server? can you tell me that?
So that's absolutely not linked to the matter that I have several plexes on my personal network. Or then prove it to me by logic computer science because I'm too in this area of expertise. 
And I don't need you to configure one more thing on your docker. I just need that you delete an option from you docker, which put your docker unusable.

**Comment by timhaak** [comment]
Once again my problem was about how you asked. Ie hurry up and fix.

Totally possible there is a bug, but people will look at it and fix when they have time.

None of us get anything by providing this except possibly helping people.

If you need it fixed sooner then provide a pull request or fork and build it. (It's not actually doing that much).

Otherwise accept that you are getting something free that people have no obligation to fix or get it to work for you.

Must say your attitude (and some other peoples) is actually making me think of deleting this and all the other docker images.

Anyway I've now pushed an update that by default set the PLEX_DISABLE_SECURITY to on by default. (Actually wasn't involved with this stuff, though it was added due to another user who was going on out security)

So give the docker hub servers some time to rebuild the image. Then do a pull.

You may need to delete your configs.
