### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by JavierMartinz** [timhaak/docker-plex#66]
I have Plex installed **without Docker** on a local machine and I can add Internet authentication if somebody try to access to it throught my Internet IP addres and the Plex port. However, if I install it using this container I can't see the authentication, it's never asked. Am I doing anything wrong or this is not possible **using Docker**?

**Comment by timhaak** [comment]
I'm not 100% sure how plex's auth works.

Though you should be able to do it.

Try setting the PLEX_DISABLE_SECURITY environment variable to 0

ie --env PLEX_DISABLE_SECURITY=0

One thing to be aware the ip that Plex will see is not the pc/server IP unless you are using --net=host.

It's normally in the 172.16.0.0/12 range. 

The quick fix is use  --net=host in your docker run.

If you are wanting to do multiple versions of plex on the same server you won't be able to use that flag due to port collisions.

**Comment by JavierMartinz** [comment]
I already tried the `PLEX_DISABLED_SECURITY`environment variable. I think the issue is that for Plex the client is always the Docker host. I mean, when I see the logs the client ip logged is always the Docker host, so it gets detected as a LAN connection instead of an external connection and I think that's the problem

**Comment by timhaak** [comment]
Hmm it's possible though you should be seeing the external IP's.

Did you try running with --net=host. Your then using the external networking directly so it should be as close to running it normally as you can.

I know some people use the image to run multiple versions on shared host. So I image it must be possible to enable auth.

Unfortunately I don't have time right now to test and see if I can see what's happening.

**Comment by timhaak** [comment]
Ok did a quick google.

You can try setting the "--userland-proxy=false"

For the daemon.

https://github.com/docker/docker/issues/15086

**Comment by JavierMartinz** [comment]
I know this is not an issue related to this specific container, but it still not working... I tried also with `--net=host`and now in the logs is showed my external public IP, all good so far but it still allowing me to access without authentication

**Comment by timhaak** [comment]
Are you sure your plex is set to ask for authentication? Also what are your allow ranges.

If plex is getting the correct IPs then it means that for some reason plex is not asking for auth.

Check under 

What is in the list for  "List of networks that are allowed without auth".  This is in settings->server->network settings.

If those are all correct I would check your xml preference file.

Unfortunately if those don't help you'll have to ask on the plex forums as if the application isn't asking for auth once it's seeing the correct IP's then problems is somewhere inside the application.

**Comment by JavierMartinz** [comment]
I set the hosts without auth to `8.8.8.8/255.255.255.255` just to test

```xml
<?xml version="1.0" encoding="utf-8"?>
<Preferences MachineIdentifier="id" ProcessedMachineIdentifier="id"
AnonymousMachineIdentifier="id" MetricsEpoch="1"
allowedNetworks="8.8.8.8/255.255.255.255"
AcceptedEULA="1" FriendlyName="Name" PlexOnlineToken="myToken"
collectUsageData="0" PublishServerOnPlexOnlineKey="1"
LastAutomaticMappedPort="0" ManualPortMappingMode="1"
PlexOnlineMail="myEmail@gmail.com" PlexOnlineUsername="blahBlah" CertificateVersion="2"
PubSubServerPing="21" PlexOnlineHome="1" DlnaEnabled="0"
LanguageInCloud="1" GdmEnabled="0" disableRemoteSecurity="0"
CloudSyncNeedsUpdate="0"
FSEventLibraryPartialScanEnabled="1"
FSEventLibraryUpdatesEnabled="1" ScheduledLibraryUpdatesEnabled="1">172.17.0.0/24</Preferences>
```

**Comment by timhaak** [comment]
Unfortunately I don't really use the preference xml as my use case is quite simple. 

If the application is getting the correct IP's and not asking for auth for some reason there must be a setting that's saying it must not ask for auth. 

So it means that your problem now is somewhere with the plex application. 

I do believe the initial problem was the application not getting the correct IP which you've now solved.

As said you'll now have to follow up on the plex forums as you'll be able to get help for the application side there.

We are not affiliated with plex, we just provide the docker build to help people.

So once it's not a problem on the docker side we can't help that much. Since the application is now getting the correct IPs it means that everything on the docker side is now correct. 

Though if you find the solution I would be interested to hear what it is and if it's something that can be added to the startup scripts.

I'll leave this open for now so if someone else knows a solution or if you find one it can be added here.

**Comment by JavierMartinz** [comment]
Thanks @timhaak, I really appreciate your help

**Comment by GLedoussal** [comment]
Hello,

I've the same problem. When doing a fresh install with docker, the web interface asks for an authentication. But after restarting the docker container, no more authentication. The only way I found to get it back is to delete the container, removing the old plex folder, removing the old server from the "My devices" on plex.tv website and then relaunching the container.

**Comment by laouache** [comment]
Hi, yesterday, i found why.

I tried to use the PLEX_TOKEN variable with a newly created plexconfig directory.
And you have an error in first creating preferences.xml and define conf afterwards in start.sh

I activated DEBUG option like you see in docker-compose.zml below 👍 
plex-media-server:
  image: "timhaak/plex"
  container_name: plex-media-server
  ports:
      - "32400:32400"
  environment:
    PLEX_USERNAME: ${PLEX_LOGIN}
    PLEX_PASSWORD: ${PLEX_PASSWORD}
    DEBUG: "true"
    PLEX_DISABLE_SECURITY: 0
  volumes:
      - ${MEDIA}:/data
      - ${PLEX_CONFIG}:/config
  restart: always
  hostname: ${PLEX_HOSTNAME}

and like you can see in this file 
[log.txt](https://github.com/timhaak/docker-plex/files/328043/log.txt)

you have an error : failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"

After resolving, I have others errors. So i will submit to you a merge request soon to correct this, if you agree.

**Comment by timhaak** [comment]
@laouache Thanks :)

Yup more than happy to get a pull request.

**Comment by timhaak** [comment]
Ok just merged @laouache patch.

If the people that are having a problem with this could pull the new image in about 20 minutes and see if it fixes your problems.

**Comment by GLedoussal** [comment]
It's getting worse for me, no more installation wizard and still no authentication :/

**Comment by timhaak** [comment]
I'm assuming since there hasn't been anyone else adding anything to this that its fixed.

**Comment by robertbarrett** [comment]
Not fixed. I was helping a friend setup her plex server, and noticed this problem.

Steps:
1) setup by running: 

`docker run --restart=always -d --name plex --net=host -v /home/dockeruser/configs/plex:/config -v /mnt/nas/media:/data/media timhaak/plex`

2) forward a port on my router from outside to the machine running docker.

3) in the plex server settings, check the allowed subnets without auth. By default this seems to be 172.17.0.0/16 and 192.168.1.0/24 (my LAN).

4) try access <globalip>:<plexport>/web from any external device (not on my lan). It loads straight away, no authentication required.

**Comment by flungo** [comment]
My understanding for why this is the default it that since `--net=host` is not the default or recommended installation, without disabling the security by default, the `PLEX_ALLOWED_NETWORKS` will only contain the docker network subnet (by default `172.16.17.0/16`) and not be accessible on any machine other than the docker host - which for some may be headless.

The instructions are designed to make it easy to get set up in the typical usecase: running Plex for your local network. If the end user had to manually set `PLEX_ALLOWED_NETWORKS` then it starts becoming more complicated, however, I would not be adverse to removing `PLEX_DISABLE_SECURITY=1` from the `Dockerfile` and adding it to the instructions in the `README.md` (in the example command) providing that the reason for the security being disabled is explained as well as the risk of doing this if port forwarding will be used to allow WAN access with a link explaining how to correctly set the `PLEX_ALLOWED_NETWORKS` variable.

I am not able to confirm or test what I have said here otherwise I would do a PR with these changes. If someone could confirm by testing and make these changes I think they would be beneficial. @timhaak do you think it would be better to move this default from the `Dockerfile` into the example command?
