### ISSUE TITLE
no such container: plex

### ISSUE THREAD

**Issue by jakebullet70** [timhaak/docker-plex#78]
i followed all the commands to install plex.

i used
docker pull timhaak/plex
and watch as every thing seems t o get downloaded and installed.

then.
docker rm -f plex
but comes back with. no such container: plex

i then do a docker ps -a and do not see plex?
If I re-run docker pull timhaak/plex it tells me it is already installed.

What am I missing?
Thanks

![image](https://cloud.githubusercontent.com/assets/14124210/18315483/dba1d6f2-751f-11e6-859f-3874e9ea7eec.png)

**Comment by timhaak** [comment]
Hi

I think your getting pull and run confused.

Pull pulls the image locally.

Run docker images to see local images.

Once you then do a docker run you'll see it under docker ps.

If the container has stopped you'll need to add docker ps -a.

To be able to do a docker rm <name>. You'll have to --name to the docker run.

Otherwise you can use the container id or auto generated name. (This you'll see with the docker ps.)

Please see the readme for examples of a run command.

For more information on run, ps, rm, pull, etc please see the docker documents.
