### ISSUE TITLE
Add token to plex pass download url fetch

### ISSUE THREAD

**Issue by timhaak** [timhaak/docker-plex#82]
Add token to plex pass download url fetch

**Comment by boistordu** [comment]
I have done some testing for you guys today about this bug. 
this paragraph : 

`    RUN if [ "${PLEX_PASS}" = "true" ]; then PLEX_URL=${PLEX_PASS_URL}; fi && \
    PLEX_JSON=$(curl -s $PLEX_URL | jq -r '.computer.Linux.releases[] | select(.build=="linux-ubuntu-x86_64" and .distro=="ubuntu") | .') && \
    PLEX_DOWNLOAD=$(echo $PLEX_JSON | jq -r '.url') && \
    PLEX_CHECKSUM=$(echo $PLEX_JSON | jq -r '.checksum') && \
    wget -O plex_server.deb $PLEX_DOWNLOAD && \
    echo "$PLEX_CHECKSUM *plex_server.deb" | sha1sum -c - && \
    dpkg -i plex_server.deb && \`


so of course if you don't put credentials in it it won't work because the plex website is a protected one.
So I've modify it in : 
`    RUN if [ "${PLEX_PASS}" = "true" ]; then PLEX_URL=${PLEX_PASS_URL}; fi && \
    PLEX_JSON=$(curl --netrc-file credentials -s $PLEX_URL | jq -r '.computer.Linux.releases[] | select(.build=="linux-ubuntu-x86_64" and .distro=="ubuntu") | .') && \
    PLEX_DOWNLOAD=$(echo $PLEX_JSON | jq -r '.url') && \
    PLEX_CHECKSUM=$(echo $PLEX_JSON | jq -r '.checksum') && \
    wget -O plex_server.deb $PLEX_DOWNLOAD && \
    echo "$PLEX_CHECKSUM *plex_server.deb" | sha1sum -c - && \
    dpkg -i plex_server.deb && \`

and I've put my credentials in a file. From a native system it works (not the building of the docker container, I mean this command). 

It doesn't work at the build of the docker and still download the 1.1.4 in place of the 1.2.2 
so i've modified again to identify the problem 
`    
ENV PLEX_URL="https://plex.tv/api/downloads/1.json?channel=plexpass" \
    PLEX_PASS_URL="https://plex.tv/api/downloads/1.json?channel=plexpass"
   #RUN if [ "${PLEX_PASS}" = "true" ]; then PLEX_URL=${PLEX_PASS_URL}; fi && \
    RUN PLEX_JSON=$(curl -u something:password -s $PLEX_URL | jq -r '.computer.Linux.releases[] | select(.build=="linux-ubuntu-x86_64" and .distro=="ubuntu") | .') && \
    PLEX_DOWNLOAD=$(echo $PLEX_JSON | jq -r '.url') && \
    PLEX_CHECKSUM=$(echo $PLEX_JSON | jq -r '.checksum') && \
    wget -O plex_server.deb`

(replace the something and password by your login and password of plexpass subsciber) still it doesn't take the good file but it takes the good one on a native system. 
So the if is not in question here, the credentials file is not in question either since it still doesn't work.

does anyone know if docker has a problem or some limitation with curl?

**Comment by boistordu** [comment]
and by the way @timhaak sorry for the other time but I hate when dev (as me) doesn't test globally their build, it remembers me too much careless people.

**Comment by timhaak** [comment]
Hi. I've tested command line (not in docker) and it didn't work for me.

So more something with the script.

Curl wouldn't work differently in docker.

**Comment by boistordu** [comment]
okey that's strange. me it worked outside of docker and in a x2go docker. I mean the command line in a terminal. Do you want that we exchange by mail? I can't obviously put the command line here with my login and password ^^or you sure that you didn't let a point or something ?

**Comment by boistordu** [comment]
and yeah I guess it wouldn't be a difference but I'm not sure about the whole build thing if it wouldn't mess up the command line in some way. by the way I've only tested in ubuntu 14.04 and ubuntu 16.04 and curl gave me the good answer to the request so not 1.4.4 but 1.22 or something like that, I don't remember exactly.

**Comment by timhaak** [comment]
I've just pushed an update that should fix this.

**Comment by boistordu** [comment]
maybe we should update the readme since you are using a bypass to our problem by using something else which use other variables no?

**Comment by timhaak** [comment]
You can send a pull request for the Readme.

Though the variables are related to the building where the readme is more related to running the docker image. 

At some point you have to pass a username and password to the system.

So the only way to do that is via build args. 

If you look at the travis file you'll see and example.

Otherwise just pull timhaak/plexpass which has it all done for you.

**Comment by boistordu** [comment]
yup you are totally right, not totally convinced either that readme have to be updated. 
thanks anyway
