### ISSUE TITLE
Natif support for RAR files

### ISSUE THREAD

**Issue by disaster37** [timhaak/docker-plex#89]
Hi,

I have extended your image with rar2fs. It's permit to look movies without unrar them (like in XBMC).
I have added new environment variable called "ENABLED_RAR2FS" to do that, and then in librairy you must to use "/data_unrar"  instead of "/data".

RAR2FS mount new FS with fuse, so when you run docker you must to add SYS_ADMIN capabilities and bind /dev/fuse ;)

You can try webcenter/plex if you wan't. Are you interested by a PR ?

**Comment by flungo** [comment]
Since this is a niche use case and requires additional dependencies and libraries I suggest not integrating and that being an extension of this image is the better way to do it - only adding the overhead for the people who want it.

From a design standpoint, I don't know if it would work but I would be interested to know if you can create a rar2fs image to act as a middleware and use `--volumes-from` to access the fuse filesystem. I have a feeling the `--volumes-from` flag won't use the fuse filesystem mounted by the container but the original volume that the container was started with. If it is possible, your rar2fs image will become way more flexible (not restricted to usage with Plex) and you won't have to worry about upstream updates.

**Comment by disaster37** [comment]
After some test, there are no way to do that. Like you say, is not supported to use volume-from with a fuse filesystem.

**Comment by timhaak** [comment]
@disaster37 think was @flungo was trying to say was to rather build an new image using this one as base and extending it to have the extra functionality you wanted.

As plex now has it's own docker container you may want to also check with them.

https://github.com/plexinc/pms-docker
